sensor:
  - platform: mqtt
    name: "Dining Room Window"
    state_topic: "windowStatus/diningRoom"
  - platform: mqtt
    name: "Kitchen Window"
    state_topic: "windowStatus/kitchen"
  - platform: mqtt
    name: "Family Room Window 1"
    state_topic: "windowStatus/familyRoom1"
  - platform: mqtt
    name: "Family Room Window 2"
    state_topic: "windowStatus/familyroom2"
  - platform: mqtt
    name: "Family Room Window 3"
    state_topic: "windowStatus/familyroom3"
  - platform: mqtt
    name: "Playroom Window"
    state_topic: "windowStatus/playroom"